# Generated by Django 4.1.13 on 2024-01-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('hid', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('source_name', models.CharField(max_length=64, unique=True)),
                ('detail', models.TextField()),
                ('picture', models.CharField(max_length=64)),
                ('grade', models.CharField(choices=[('C', 'Common'), ('R', 'Rare'), ('E', 'Epic'), ('A', 'Arcane'), ('S', 'Secret')], default='C', max_length=10)),
                ('type', models.CharField(choices=[('P', 'Plant'), ('L', 'Location'), ('A', 'Area'), ('C', 'Challenge')], default='P', max_length=10)),
                ('ranking_top', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('profile_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('picture', models.CharField(max_length=64, null=True)),
                ('ownership_rankings', models.JSONField(default=dict)),
                ('ownership_count', models.IntegerField(default=0)),
                ('last_activity_capture', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
